name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checar repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instalar Node.js e pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      # 3. Validar Node
      - name: Verificar versão do Node
        run: node -v

      # 4. Instalar dependências
      - name: Instalar dependências
        run: pnpm install

      # 5. Build do projeto
      - name: Build do projeto
        run: pnpm build

      # 6. Deploy da imagem Docker
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/infnet-app:latest .
      
      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/infnet-app:latest
